print("scriptisnotwork")
 print("Welcome Salad X Hub")
 local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
 local Window  = Library.CreateLib("Salad X Hub", "BloodTheme")
 local Tab     = Window:NewTab("notify the news") 
 local Section = Tab:NewSection("Notice again, this script is")
 local Section = Tab:NewSection("just giving away scripts from other camps that are free.")
 local Section = Tab:NewSection("additional questions DM xq_srrrr#0781")
 local Tab     = Window:NewTab("Blox fruits")
 local Section = Tab:NewSection("Rejoin")
 Section:NewButton("click to use", "Rejoin", function() 
 print("Clicked")loadstring(game:HttpGet("https://raw.githubusercontent.com/AkiraNusZ/TeleportRejoin/main/Rejoin.lua"))() 
end) 
local Section = Tab:NewSection("Salad X Hub")
 Section:NewButton("click to use", "Main Hub", function()
 print("Clicked")loadstring(game:HttpGet("https://raw.githubusercontent.com/AkiraNusZ/SwitchHubNoob/main/FreeCr.XenonHub.noob"))() 
end) 
local Section = Tab:NewSection("Unique Hub") 
Section:NewButton("click to use", "Uique Hub trash", function() 
print("Clicked")loadstring(game:HttpGet("https://raw.githubusercontent.com/AkiraNus/UniquehubKak/main/FreeCr.Xenonhub"))(); 
end)
local Section = Tab:NewSection("Fake Level") 
Section:NewButton("click to use", "Troll Friend", function()
 print("Clicked")loadstring(game:HttpGet('https://raw.githubusercontent.com/SHAREHACK/allscript/main/level'))() 
end)
 local Section = Tab:NewSection("Zen Hub MB/PC") 
 Section:NewButton("click to use", "Script Hub", function() 
 print("Clicked")loadstring(game:HttpGet("https://raw.githubusercontent.com/Kaizenofficiall/ZenHub/main/Loader", true))() 
end) 
local Section = Tab:NewSection("Thunder Z Kaitun") 
Section:NewButton("click to use", "Kaitun", function() 
print("Clicked")loadstring(game:HttpGet("https://raw.githubusercontent.com/ThunderZ-05/HUB/main/Kaitun"))() 
end) 
local Section = Tab:NewSection("Viper hub") 
Section:NewButton("click to use", "My Friend Hub", function() 
print("Clicked")if not syn then getgenv().syn={queue_on_teleport=queue_on_teleport or function()end}end loadstring(game:HttpGet("https://raw.githubusercontent.com/onehalla/1hallascripts/master/release/viperhub.lua", true))() 
end) 
local Section = Tab:NewSection("Mukuro Hub") 
Section:NewButton("click to use", "Script Hub", function() 
print("Clicked")loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")() 
end) 
local Section = Tab:NewSection("Ripper Hub") 
Section:NewButton("click to use", "Script Hub", function() 
print("Clicked")loadstring(game:HttpGet('https://raw.githubusercontent.com/xDestinyx/RipperHub/main/Loader.lua'))(); 
end) 
Section   = Tab:NewSection("Comming Soon") 
local Tab = Window:NewTab("DOORS") 
Section   = Tab:NewSection("Vynixius hub") 
Section:NewButton("click to use", "Script Hub", function() 
print("Clicked")loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Vynixius/main/Doors/Script.lua"))() 
end) 
local Tab     = Window:NewTab("Credit ") 
Section       = Tab:NewSection("xq_srrrr #0781") 
local Section = Tab:NewSection("https://discord.gg/uYJtxvvwAU") 
local Tab     = Window:NewTab(".") 
Section       = Tab:NewSection("Empty") 
local Tab     = Window:NewTab(".") 
Section       = Tab:NewSection("Empty") 
local Tab     = Window:NewTab(".") 
Section       = Tab:NewSection("Empty") 
local Tab     = Window:NewTab(".") 
Section       = Tab:NewSection("Empty") 
local Tab     = Window:NewTab(".") 
Section       = Tab:NewSection("Empty") 
local Tab     = Window:NewTab(".") 
Section       = Tab:NewSection("Xenon hub Script Secret") 
Section:NewButton("click to use", "Secret", function() 
print("Clicked")loadstring(game:HttpGet('https://raw.githubusercontent.com/Xenon-Trash/Loader/main/Loader.lua')){58000,47231,89761,60830,62465,147762}
end) 
Section = Tab:NewSection("Maru Hub Script Secret") 
Section:NewButton("click to use", "Secret", function() 
print("Clicked")loadstring(game:HttpGet("https://raw.githubusercontent.com/AkiraNusZ/ScriptDev/main/Dev"))() 
end)
